//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttachmentMover.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AttachmentMover.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.azureblob.
        /// </summary>
        internal static string AAzureBlob {
            get {
                return ResourceManager.GetString("AAzureBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already existing.
        /// </summary>
        internal static string AlreadyExisting {
            get {
                return ResourceManager.GetString("AlreadyExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b.dynamics.
        /// </summary>
        internal static string BDynamics {
            get {
                return ResourceManager.GetString("BDynamics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to D365 Server.
        /// </summary>
        internal static string ConnectedToD365Server {
            get {
                return ResourceManager.GetString("ConnectedToD365Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue? (y/N).
        /// </summary>
        internal static string DoYouWantToContinue {
            get {
                return ResourceManager.GetString("DoYouWantToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files will be fetched from:.
        /// </summary>
        internal static string FilesWillBeFetchedFrom {
            get {
                return ResourceManager.GetString("FilesWillBeFetchedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World.
        /// </summary>
        internal static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your mode of import:.
        /// </summary>
        internal static string ModeOfImport {
            get {
                return ResourceManager.GetString("ModeOfImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected mode of import is invalid or is not yet supported..
        /// </summary>
        internal static string ModeOfImportInvalid {
            get {
                return ResourceManager.GetString("ModeOfImportInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Files to upload.
        /// </summary>
        internal static string NoFilesToUpload {
            get {
                return ResourceManager.GetString("NoFilesToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected to D365 Server.
        /// </summary>
        internal static string NotConnectedToD365Server {
            get {
                return ResourceManager.GetString("NotConnectedToD365Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process is completed. Check the log files, Click any key to close.
        /// </summary>
        internal static string ProcessCompletedCheckLogFiles {
            get {
                return ResourceManager.GetString("ProcessCompletedCheckLogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staging Entity create with ID.
        /// </summary>
        internal static string StagingEntityWithCreateID {
            get {
                return ResourceManager.GetString("StagingEntityWithCreateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the files in the folder are not supported for uploading..
        /// </summary>
        internal static string UnsupportedFilesFound {
            get {
                return ResourceManager.GetString("UnsupportedFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploaded successfully.
        /// </summary>
        internal static string UploadedSuccessfully {
            get {
                return ResourceManager.GetString("UploadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which approach do you wish to proceed with.
        /// </summary>
        internal static string WhichApproachToProceed {
            get {
                return ResourceManager.GetString("WhichApproachToProceed", resourceCulture);
            }
        }
    }
}
